graph = {
    'hostel_1': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                 'brabers', 'GIKCAFE'],

    'hostel_2': ['hostel_1', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_3': ['hostel_2', 'hostel_1', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_4': ['hostel_2', 'hostel_3', 'hostel_1', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_5': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_1', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_6': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_1', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_7': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_1', 'hostel_8', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_8': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_1', 'hostel_9', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_9': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_1', 'hostel_10',
                 'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                 'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                 'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_10': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8',
                  'hostel_9', 'hostel_1',
                  'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                  'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                  'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_11': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                  'hostel_1', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                  'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                  'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'hostel_12': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                  'hostel_11', 'hostel_1', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                  'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                  'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'Raju_Shop': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                  'hostel_11', 'hostel_12', 'hostel_1', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                  'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                  'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'Ayyan_Shop': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                   'hostel_11', 'hostel_12', 'Raju_Shop', 'hostel_1', 'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                   'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                   'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'barber_shop': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'hostel_1', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'Allied_Bank': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'hostel_1', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'Guest_House': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'hostel_1', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'Faculty_Club': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5', 'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                     'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop', 'barber_shop', 'Allied_Bank', 'Guest_House', 'hostel_1',
                     'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                     'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'GIKI_Main_Gate': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                       'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                       'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                       'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                       'hostel_1', 'sports_ground', 'Mess_Hall_1', 'Mess_Hall_2',
                       'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                       'faculty_houses', 'FCSE', 'FMCE', 'FES',
                       'FME', 'Academic_block', 'brabers', 'GIKCAFE'],

    'sports_ground': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                      'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                      'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                      'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                      'GIKI_Main_Gate', 'hostel_1', 'Mess_Hall_1',
                      'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                      'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                      'brabers', 'GIKCAFE'],

    'Mess_Hall_1': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                    'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                    'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'hostel_1',
                    'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                    'brabers', 'GIKCAFE'],

    'Mess_Hall_2': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                    'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                    'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                    'hostel_1', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                    'brabers', 'GIKCAFE'],

    'Mess_Hall_3': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                    'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                    'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                    'Mess_Hall_2', 'hostel_1', 'Mess_Hall_4', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                    'brabers', 'GIKCAFE'],

    'Mess_Hall_4': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                    'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                    'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                    'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                    'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                    'Mess_Hall_2', 'Mess_Hall_3', 'hostel_1', 'Administration',
                    'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                    'brabers', 'GIKCAFE'],

    'Administration': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                       'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                       'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                       'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                       'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                       'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                       'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                       'brabers', 'GIKCAFE'],



    'faculty_houses': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                       'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                       'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                       'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                       'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                       'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                       'hostel_1', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                       'brabers', 'GIKCAFE'],

    'FCSE': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
             'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
             'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
             'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
             'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
             'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
             'faculty_houses', 'hostel_1', 'FMCE', 'FES', 'FME', 'Academic_block',
             'brabers', 'GIKCAFE'],

    'FMCE': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
             'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
             'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
             'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
             'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
             'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
             'faculty_houses', 'FCSE', 'hostel_1', 'FES', 'FME', 'Academic_block',
             'brabers', 'GIKCAFE'],

    'FES': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
            'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
            'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
            'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
            'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
            'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
            'faculty_houses', 'FCSE', 'FMCE', 'hostel_1', 'FME', 'Academic_block',
            'brabers', 'GIKCAFE'],

    'FME': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
            'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
            'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
            'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
            'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
            'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
            'faculty_houses', 'FCSE', 'FMCE', 'FES', 'hostel_1', 'Academic_block',
            'brabers', 'GIKCAFE'],

    'Academic_block': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                       'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                       'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                       'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                       'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                       'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                       'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'hostel_1',
                       'brabers', 'GIKCAFE'],

    'brabers': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                'hostel_1', 'GIKCAFE'],

    'GIKCAFE': ['hostel_2', 'hostel_3', 'hostel_4', 'hostel_5',
                'hostel_6', 'hostel_7', 'hostel_8', 'hostel_9', 'hostel_10',
                'hostel_11', 'hostel_12', 'Raju_Shop', 'Ayyan_Shop',
                'barber_shop', 'Allied_Bank', 'Guest_House', 'Faculty_Club',
                'GIKI_Main_Gate', 'sports_ground', 'Mess_Hall_1',
                'Mess_Hall_2', 'Mess_Hall_3', 'Mess_Hall_4', 'Administration',
                'faculty_houses', 'FCSE', 'FMCE', 'FES', 'FME', 'Academic_block',
                'brabers', 'hostel_1'],

}

graph('hostel_1')
